### ISSUE TITLE
Can we deploy scrapers?

### ISSUE THREAD

**Issue by jodizzle** [opensyllabus/osp-pipeline#127]
The deprecated osp-deploy had facilities for both deploying spark clusters and deploying scraper clusters.  The spark deployment has been copied over to the pipeline in the new docker approach, but can the pipeline also handle scraper deployment?

Alternatively, should it?  Could we just keep using some version of osp-deploy for the scrapers?  I'm also wondering if it would make sense for osp-scraper to have it's own `deploy/` folder.  That seems appropriate (though I saw https://github.com/opensyllabus/osp-deploy/issues/5 was closed, so maybe I'm out of the loop.)

Links from osp-deploy:
- [Notes on deploying a scraper cluster.](https://github.com/opensyllabus/osp-deploy/blob/8f23635136d434dfba66634db5089cd6f795148b/README.md#deploy-a-scraper-cluster)  You can also browse the history at this commit for more details.
- [Old scraper roles](https://github.com/opensyllabus/osp-deploy/tree/8f23635136d434dfba66634db5089cd6f795148b/roles/scraper).  The scraper setup used [ansible-redis](https://github.com/DavidWittman/ansible-redis/tree/69b40e6462073cd247c63db8e30a9d42e91a21e1).

**Comment by wearpants** [comment]
No the pipeline should not deploy scrapers

Scraper should have it's own deploy system, in the same repo as code

On Jan 21, 2018 1:13 AM, "jodizzle" <notifications@github.com> wrote:

The deprecated osp-deploy had facilities for both deploying spark clusters
and deploying scraper clusters. The spark deployment has been copied over
to the pipeline in the new docker approach, but can the pipeline also
handle scraper deployment?

Alternatively, should it? Could we just keep using some version of
osp-deploy for the scrapers? I'm also wondering if it would make sense for
osp-scraper to have it's own deploy/ folder. That seems appropriate (though
I saw opensyllabus/osp-deploy#5
<https://github.com/opensyllabus/osp-deploy/issues/5> was closed, so maybe
I'm out of the loop.)

Links from osp-deploy:

   - Notes on deploying a scraper cluster.
   <https://github.com/opensyllabus/osp-deploy/blob/8f23635136d434dfba66634db5089cd6f795148b/README.md#deploy-a-scraper-cluster>
   You can also browse the history at this commit for more details.
   - Old scraper roles
   <https://github.com/opensyllabus/osp-deploy/tree/8f23635136d434dfba66634db5089cd6f795148b/roles/scraper>.
   The scraper setup used ansible-redis
   <https://github.com/DavidWittman/ansible-redis/tree/69b40e6462073cd247c63db8e30a9d42e91a21e1>
   .

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/opensyllabus/osp-pipeline/issues/127>, or mute the
thread

**Comment by wearpants** [comment]
Let's open a ticket in osp-scraper for moving the code out of osp-deploy. Note we do *not* need to dockerland this at present. @lily-mayfield

**Comment by wearpants** [comment]
Let's open a ticket in osp-scraper for moving the code out of osp-deploy. Note we do *not* need to dockerland this at present. @lily-mayfield

**Comment by wearpants** [comment]
Let's open a ticket in osp-scraper for moving the code out of osp-deploy. Note we do *not* need to dockerland this at present. @lily-mayfield
