### ISSUE TITLE
Integrate miscellanious documents

### ISSUE THREAD

**Issue by jodizzle** [opensyllabus/osp-pipeline#147]
We currently have several document dumps that come from miscellaneous sources -- like the Bennington collection, except not just from one school, and not as organized -- and need to be processed in the pipeline somehow.  Given current design, this would probably involve the creation of a "MiscDocument" model/bucket/source, though some code could probably be shared with the Bennington model.

**Comment by wearpants** [comment]
What are these and where are they from? How/where are they stored?

On Feb 19, 2018 2:22 AM, "jodizzle" <notifications@github.com> wrote:

We currently have several document dumps that come from miscellaneous
sources -- like the Bennington collection, except not just from one school,
and not as organized -- and need to be processed in the pipeline somehow.
Given current design, this would probably involve the creation of a
"MiscDocument" model/bucket/source, though some code could probably be
shared with the Bennington model.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/opensyllabus/osp-pipeline/issues/147>, or mute the
thread

**Comment by jodizzle** [comment]
@wearpants They are documents collected by Joe from various sources.  They aren't WARCs or any special file format, just raw docs.

Currently, they're just in zipfiles that I have copies of.

**Comment by wearpants** [comment]
Maybe stick them in a bucket on S3, with filenmaes based on md5 of contents?

How many we talking about?

**Comment by jodizzle** [comment]
It's probably around 20k documents, though there may be more trickling in as time goes on.  Most/all of them are syllabi.

The documents already have filenames, and some of them are organized into subfolders (the archive isn't "flat"), so I think it would make the most sense to unzip and store them in an S3 bucket as-is.  Then we can ID them by a `path`, similar to `BenningtonDocument`, and then store `data` and `data_md5` like normal.  I don't think any other fancy fields or file modifications would be required.

**Comment by wearpants** [comment]
it's appealing to use md5 as a name if there are conflicting
paths/filenames, if we get the same file a 2nd time, etc..

Subfolders are a tremendous pain with our current architecture and I'd like
to avoid them.

Check out https://en.wikipedia.org/wiki/Content_addressable_network for the
theory here

**Comment by jodizzle** [comment]
So I think I understand your idea here, but what makes handling subfolders a pain?  All the paths in the bucket would be collected up by `bucket.list_paths()`, as is done in [`load_bennington_documents.py`](https://github.com/opensyllabus/osp-pipeline/blob/bddc60c1a9fd3d2ff2c65d0a9005e6e1b52228e0/osp_pipeline/corpus/jobs/load_bennington_documents.py#L30), and I'm pretty sure we would have to call that method (or a method like it) even if the bucket didn't have subfolders.  (Technically, S3 buckets are already "flat" and the "subfolders" are just part of the keys, but that's kind of a pedantic point.)

Also, while I don't think there's a current need for the filenames or paths, I'd err towards not destroying metdata and just leaving the files as-is.
