### ISSUE TITLE
cluster shutdown script

### ISSUE THREAD

**Issue by wearpants** [opensyllabus/osp-pipeline#90]

**Comment by davidmcclure** [comment]
This should be simple, looks like we can just use the same `ec2` module in Ansible, and set `state=absent`.

http://docs.ansible.com/ansible/latest/ec2_module.html

Before experimenting with this, let's make sure we've got termination protection on the important instances (namely osp-www), since a mistake here could take the public site offline.

**Comment by SlimeMaid** [comment]
Needs to cean up ebs volumes because it causes probem, see this log below:

```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "wait for instances running timeout on Sat Dec 23 13:21:00 2017"}

...

Add Comment Collapse  This snippet was truncated for display: see it in full.
```

pete [12:24 PM]  
@lily can you take a look at this when you're back online? happens consistently
 
have a good holiday until then

(guess that goes for EC2 as well!)

lily 
 [12:24 PM]  
@pete this is bizarre nothing changed in scriptland since it was working hrm

I wonder if amazon is having troubles

„wait for instances running timeout on Sat Dec 23 13:21:00 2017"}”
 
Googled on phone: https://groups.google.com/forum/m/#!topic/ansible-project/QMmd53UalDU

pete [4:09 PM]  
hmm, seems likely @lily https://console.aws.amazon.com/ec2/v2/home?region=us-east-1#Volumes:sort=desc:createTime

i thought i tell amazon to destroy ebs volumes when i terminate, but maybe that's just the root, or not happening for some reason

#90 shutdown script would be real helpful here

*cleans them up*

yup, that ws the problem
```

**Comment by SlimeMaid** [comment]
Actually cleaning up EBS problem isn't what I'd want in a shutdown script, I want:

https://stackoverflow.com/questions/45247521/how-to-set-delete-on-termination-for-boot-volume-in-ec2-volume-using-ansible

**Comment by SlimeMaid** [comment]
Regarding cleaning up EBS volumes: https://github.com/opensyllabus/osp-pipeline/commit/0b263be6b2460ff83c9962b82cc1c3898fc08ca6 (solved; no need to include cleaning of EBS volumes in script)

**Comment by lily-mayfield** [comment]
Okay I can do this pretty easily I just need to require awscli as a depend and use `terminate-instances`

http://docs.aws.amazon.com/cli/latest/reference/ec2/terminate-instances.html

**Comment by lily-mayfield** [comment]
Resolved in https://github.com/opensyllabus/osp-pipeline/releases/tag/v0.10.1
